
export default {
    ruleList:[
        {
            value:0,
            label:'预定须知',
            desc:'',
            name:'ticketRule',
        },
        {
            value:1,
            label:'取票说明',
            desc:'',
            name:'',
        },
        {
            value:2,
            label:'退票说明',
            desc:'',
            name:'refundRule',
        }   
    ],
    typeMap:[
        {
            value:1,
            label:'散客票'
        },
        {
            value:2,
            label:'粤通套票'
        },
        {
            value:3,
            label:'珠澳居民'
        },
        {
            value:4,
            label:'珠澳来回套票'
        },
        {
            value:5,
            label:'珠澳卡'
        },
        {
            value:6,
            label:'珠澳居民'
        },
        {
            value:7,
            label:'粤通公司票'
        },
        {
            value:8,
            label:'港口贵宾卡'
        }
    ],
    addValueList:[
        {
            value:1,
            label:'酒店',
            desc:''
        },
        {
            value:2,
            label:'接车服务',
            desc:''
        },
        {
            value:99,
            label:'其他',
            desc:''
        }  
    ]
}
